-- WP SQL --

DROP TABLE IF EXISTS `#__vikrestaurants_wpshortcodes`;

-- END WP SQL --

DROP TABLE IF EXISTS `#__vikrestaurants_reservation`;
DROP TABLE IF EXISTS `#__vikrestaurants_table`;
DROP TABLE IF EXISTS `#__vikrestaurants_table_cluster`;
DROP TABLE IF EXISTS `#__vikrestaurants_room`;
DROP TABLE IF EXISTS `#__vikrestaurants_room_closure`;
DROP TABLE IF EXISTS `#__vikrestaurants_shifts`;
DROP TABLE IF EXISTS `#__vikrestaurants_menus`;
DROP TABLE IF EXISTS `#__vikrestaurants_menus_section`;
DROP TABLE IF EXISTS `#__vikrestaurants_section_product`;
DROP TABLE IF EXISTS `#__vikrestaurants_section_product_option`;
DROP TABLE IF EXISTS `#__vikrestaurants_section_product_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_specialdays`;
DROP TABLE IF EXISTS `#__vikrestaurants_sd_menus`;
DROP TABLE IF EXISTS `#__vikrestaurants_custfields`;
DROP TABLE IF EXISTS `#__vikrestaurants_gpayments`;
DROP TABLE IF EXISTS `#__vikrestaurants_coupons`;
DROP TABLE IF EXISTS `#__vikrestaurants_coupon_category`;
DROP TABLE IF EXISTS `#__vikrestaurants_res_code`;
DROP TABLE IF EXISTS `#__vikrestaurants_res_menus_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_res_prod_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_config`;
DROP TABLE IF EXISTS `#__vikrestaurants_users`;
DROP TABLE IF EXISTS `#__vikrestaurants_user_delivery`;
DROP TABLE IF EXISTS `#__vikrestaurants_operator`;
DROP TABLE IF EXISTS `#__vikrestaurants_operator_log`;
DROP TABLE IF EXISTS `#__vikrestaurants_countries`;
DROP TABLE IF EXISTS `#__vikrestaurants_reviews`;
DROP TABLE IF EXISTS `#__vikrestaurants_invoice`;
DROP TABLE IF EXISTS `#__vikrestaurants_order_status`;
DROP TABLE IF EXISTS `#__vikrestaurants_stats_widget`;
DROP TABLE IF EXISTS `#__vikrestaurants_tag`;
DROP TABLE IF EXISTS `#__vikrestaurants_status_code`;
DROP TABLE IF EXISTS `#__vikrestaurants_tax`;
DROP TABLE IF EXISTS `#__vikrestaurants_tax_rule`;
DROP TABLE IF EXISTS `#__vikrestaurants_media`;
DROP TABLE IF EXISTS `#__vikrestaurants_mail_text`;

DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_menus`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_menus_entry`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_menus_entry_option`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_menus_attribute`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_menus_attr_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_topping_separator`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_topping`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_entry_group_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_group_topping_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_reservation`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_res_prod_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_res_prod_topping_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_deal`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_deal_day_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_deal_product_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_deal_free_assoc`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_stock_override`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_avail_override`;
DROP TABLE IF EXISTS `#__vikrestaurants_takeaway_delivery_area`;
DROP TABLE IF EXISTS `#__vikrestaurants_origin`;

DROP TABLE IF EXISTS `#__vikrestaurants_api_login`;
DROP TABLE IF EXISTS `#__vikrestaurants_api_login_event_options`;
DROP TABLE IF EXISTS `#__vikrestaurants_api_login_logs`;
DROP TABLE IF EXISTS `#__vikrestaurants_api_ban`;

DROP TABLE IF EXISTS `#__vikrestaurants_lang_room`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_menus`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_menus_section`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_section_product`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_section_product_option`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_takeaway_menus`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_takeaway_menus_entry`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_takeaway_menus_entry_option`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_takeaway_menus_entry_topping_group`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_takeaway_topping`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_takeaway_menus_attribute`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_takeaway_deal`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_payments`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_customf`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_tax`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_tax_rule`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_status_code`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_media`;
DROP TABLE IF EXISTS `#__vikrestaurants_lang_config`;