<?php
/** 
 * @package     VikRestaurants
 * @subpackage  core
 * @author      E4J s.r.l.
 * @copyright   Copyright (C) 2023 E4J s.r.l. All Rights Reserved.
 * @license     http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 * @link        https://vikwp.com
 */

// No direct access
defined('ABSPATH') or die('No script kiddies please!');

/**
 * Template file used to display the overlay to load
 * asynchronously the details of the selected product.
 * In case the product supports the toppings selection,
 * it will be shown here.
 *
 * @since 1.8
 */

$data = [
	/**
	 * An optional Itemid to be used when routing a URL.
	 *
	 * @var int|null
	 */
	'Itemid' => $this->itemid,
];

/**
 * The overlay used to edit a product from the cart will be
 * generated by the layout file below:
 * /components/com_vikrestaurants/layouts/blocks/tkoverlay.php (joomla)
 * /wp-content/plugins/vikrestaurants/site/layouts/blocks/tkoverlay.php (wordpress)
 *
 * @since 1.8
 */
echo JLayoutHelper::render('blocks.tkoverlay', $data);
